# Generated by Django 4.1.5 on 2023-01-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_slider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.URLField(default='#'),
        ),
    ]
