# Generated by Django 4.1.5 on 2023-01-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_store_customization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customization',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
