# Generated by Django 4.1.5 on 2023-02-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_info_desc_alter_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
