# Generated by Django 4.1.5 on 2023-01-18 20:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('logo', models.ImageField(default='logo.png', upload_to='blog/logos/%y/%m/%d')),
                ('bio', models.TextField(default='لا يوجد وصف')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('lang', models.CharField(choices=[('arabic', 'عربي'), ('english', 'english')], max_length=30)),
                ('template', models.CharField(choices=[('nour', 'nour')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(default='categorise.webp', upload_to='categories')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', ckeditor.fields.RichTextField(default='المحتوي')),
                ('image', models.ImageField(default='categorise.png', upload_to='blog/posts/%y/%m/%d')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('categorise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categories')),
            ],
        ),
    ]
