# Generated by Django 4.1.5 on 2023-01-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='categorise.png', upload_to='posts/%y/%m/%d'),
        ),
    ]
