# Generated by Django 4.1.5 on 2023-01-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_categorise_post_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
