# Generated by Django 4.1.5 on 2023-01-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_facebook_blog_instagram_blog_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='template',
            field=models.CharField(choices=[('nour', 'nour'), ('food', 'food')], max_length=30),
        ),
    ]
