# Generated by Django 4.1.5 on 2023-01-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
        migrations.AddField(
            model_name='categories',
            name='father',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_father': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categories'),
        ),
        migrations.AddField(
            model_name='categories',
            name='is_father',
            field=models.BooleanField(default=False),
        ),
    ]
