# Generated by Django 4.1.5 on 2023-01-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_categories_blog_categories_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.ForeignKey(blank=True, db_column='categories_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categories'),
        ),
    ]
