# Generated by Django 4.1.5 on 2023-01-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(blank=True, db_column='blog_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
