# Generated by Django 4.1.5 on 2023-01-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
