# Generated by Django 4.1.5 on 2023-02-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
    ]
