# Generated by Django 4.1.5 on 2023-02-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_categories_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
