# Generated by Django 4.1.5 on 2023-02-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bio',
            field=models.TextField(default='bio not found'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='template',
            field=models.CharField(choices=[('nour', 'nour')], max_length=30),
        ),
    ]
