# Generated by Django 4.1.5 on 2023-01-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_categoriesshop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesshop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
