# Generated by Django 4.1.5 on 2023-01-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_categoriesshop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='CategoriesShop',
        ),
    ]
