# Generated by Django 4.1.5 on 2023-01-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_price_delete_categoriesshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(default='logo.png', upload_to='shop/logos/%y/%m/%d'),
        ),
    ]
