# Generated by Django 4.1.5 on 2023-01-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_shop_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
    ]
