# Generated by Django 4.1.5 on 2023-01-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(20, 10), (40, 20), (60, 30), (80, 40), (100, 50)], default=60),
        ),
    ]
