# Generated by Django 4.1.5 on 2023-01-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_before_discount_shop_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='before_discount',
            new_name='discount',
        ),
    ]
