# Generated by Django 4.1.5 on 2023-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_brands',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_slider',
            field=models.BooleanField(default=True),
        ),
    ]
