# Generated by Django 4.1.5 on 2023-02-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_product_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='blog',
            new_name='shop',
        ),
    ]
