# Generated by Django 4.1.5 on 2023-01-31 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_cv_experience_alter_cv_happy_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cv',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
