# Generated by Django 4.1.5 on 2023-02-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_rename_gethub_cv_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
