# Generated by Django 4.1.5 on 2023-02-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_experience_date_from_experience_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='shop.webp', upload_to='cv/service/%y/%m/%d'),
        ),
    ]
