# Generated by Django 4.1.5 on 2023-02-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='what_he_say',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
